spring-boot-jjj:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 文件上传下载配置
  upload-path: D:/product_java/jjj_shop_multi_git_java/uploads


spring:
  datasource:
    url: jdbc:mysql://lmxdxl99.com.cn:3306/data_class_4?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20010720Lmx




  # Redis配置
  redis:
    database: 0
    port: 6379
    host: 192.168.75.128
    password: 258369

# logback.xml中有详细的日志配置
logging:
  path: D:/java/logs/multi-git

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl